spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
        cluster-name: BJ
#        metadata:
#          instance: a
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: false
server:
  port: 8010
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#解决首次加载慢的问题
ribbon:
  eager-load:
    clients: user-center
    enabled: true
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
#细粒度配置和全局配置只用把服务名称改为default
feign:
  #为feign配置sentinel
  sentinel:
    enable: true
  client:
    config:
      #想要调用微服务的名称
#      user-center:
       default:
        loggerLevel: full
  httpclient:
    #让feign使用apache httpclient做请求，而不是默认的urlconnection
    enabled: true
    #feign的最大连接数
    max-connections: 200
    #feign单个路径的最大连接数
    max-connections-per-route: 50
#为resttemplate整合sentinel
resttemplate:
  sentinel:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
